name: build and deploy to aws eb

env:
  aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}  
  aws_environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
  aws_application_name: ${{ secrets.AWS_APPLICATION_NAME }}

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore  
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: NPM Install
        run: npm install
        
      - run: pwd
      
      - run: ls -a
      
      - run: cd ./EmptyServiceStackNuxt
        
      - name: NPM Build
        run: npm run build
        
      #- name: Test
      #  run: dotnet test --no-restore --verbosity normal
        
      #- name: Create the package
      #  run: dotnet pack --configuration Release <emptynuxt>
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ env.aws_access_key }}
          aws_secret_key: ${{ env.aws_secret_key }}
          application_name: ${{ env.aws_application_name }}
          environment_name: ${{ env.aws_environment_name }}
          version_label: 119
          region: us-east-1
          deployment_package: deploy.zip
